import psycopg2
import json
from datetime import date
import psycopg
from psycopg.errors import SerializationFailure, Error
from psycopg.rows import namedtuple_row
import os
# from dotenv import load_dotenv

# If modifying these scopes, delete the file token.json.

import psycopg2
from psycopg2.extras import execute_values


conn = psycopg2.connect(os.environ['DATABASE_URL'])


def create_user_table():
    with conn.cursor() as cur:
        cur.execute(
            "DROP TABLE IF EXISTS users; CREATE TABLE IF NOT EXISTS users (id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, email VARCHAR(255), password VARCHAR(255));"
        )
    conn.commit()

create_user_table()
